language: objective-c
osx_image: xcode7.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
install:
  - gem install cocoapods --pre
  - gem install xcpretty
  - pod install
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - xcodebuild -workspace Swift-ZHI.xcworkspace -scheme "Swift-ZHI" -destination "OS=9.2,name=iPhone 6s Plus" build | xcpretty -c
